name: Manage outdated dependencies and create issue

on: 
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-outdated-dependencies:
    runs-on: macos-latest
    name: Check outdated dependencies and create issue if it doesn't exist
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Check outdated dependencies and create issue
        id: check-outdated-dependencies-and-create-issue
        uses: rudderlabs/github-action-updated-dependencies-notifier@78835fb7a62239044bee3cb4d2d3424b165663a6 # main
        with:
          outdated-dependency-names: "com.bugsnag:bugsnag-android"
          directory: "bugsnag/build.gradle"
          title: "fix: update Bugsnag SDK to the latest version"
          assignee: "desusai7"
          labels: "outdatedDependency"
          color: "FBCA04"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the github issue url
        if: steps.check-outdated-dependencies-and-create-issue.outputs.issue-url != ''
        run: echo "The Github issue url is ${{ steps.check-outdated-dependencies-and-create-issue.outputs.issue-url }}"
